### ISSUE TITLE
combined widget/output type?

### ISSUE THREAD

**Issue by stevengj** [JuliaGizmos/Interact.jl#12]
One thing that I don't like about the current `@manipulate` (besides #11 and #8) is that it relies upon `display` side effects.  Not only does this mean that it can't be easily used in a functional context, but it also means that the widgets ~~may be displayed out-of-order (since zeromq does not guarantee that messages arrive in-order, although they usually do in practice)~~ (_not true_: zmq apparently does guarantee order).

It would be nice to be able to return a single object from `@manipulate` that encapsulates both the widgets and the displayed signal result, such that calling `display` on it will display all of them together.

Unfortunately, this may be a bit tricky to implement.   Ideally you would write a `writemime` method that stitches all the data together.   But it's not so easy to stitch together, e.g. text/html widgets and text/latex signal output.  You could overload `display` (to call `display` on the widgets and signals separately) instead of `writemime`, but this could be somewhat fragile and also wouldn't solve the in-order issue.

**Comment by Keno** [comment]
Bump. I'd very much like to see this implemented. I'm doing some experimentation and this is one of the things that really annoys me about Interact.

**Comment by Keno** [comment]
Also, I'd be happy with just the first step of getting rid of the call to `display` on the julia side. I don't care too much about IPython.

**Comment by piever** [comment]
I think this is should be fixed in the latest (unreleased) Interact, based on WebIO and InteractBase.

Now if:

```
ui = @manipulate for i in 1:10
    i
end
```

`ui` is a `Widget{:manipulate}` that has a `output` and a `display` field. In this case `ui.output` is a `Observable` with value 5 (as `i` initial value is 5), whereas `ui.display` is a `Observable` containing the `WebIO.Node` that stores `ui.output`.

Feel free to reopen if some of the concerns expressed here have not been addressed (even though I suspect that if there are concerns about the display mechanism, they belong to WebIO rather than here).
