### ISSUE TITLE
"map"-ed sliders not responding in Julia v0.5

### ISSUE THREAD

**Issue by ma-laforge** [JuliaGizmos/Interact.jl#126]
I am testing out interact_nb/01-Introduction.ipynb with Julia 0.5.

I am looking at the last example with dependent widgets:
```
fx = Signal(0.0) # A float input
[...]
x = slider(0:.1:2pi, label="x")
y = map(v -> slider(-1:.05:1, value=sin(v), signal=fx, label="f(x)"), signal(x))
map(display, (x,y));
```

It seems like "map"-ed sliders (and possibly other widgets) do not update when the input parameter changes.

Am I doing something wrong here, or is Interact simply not Julia v0.5 ready yet?

**Comment by JobJob** [comment]
Thanks for reporting. Indeed, I think this was related to some recent changes in Julia. I have a simple fix for this, will make a PR soon. Note that in general, making a signal whose values are widgets of different types doesn't work atm, see: #47 but this should work since `y`'s always returns a slider.
