### ISSUE TITLE
Shared state causing `@manipulate` to fail?

### ISSUE THREAD

**Issue by xorJane** [JuliaGizmos/Interact.jl#187]
Hello! I'm using `Interact` in a jupyter notebook (version 5.0.0) with IJulia version 1.6.1 and Julia 0.6. I have multiple calls to `@manipulate` in one notebook. It seems that distinct calls to `@manipulate` share state, causing code using `@manipulate` to fail in some cases.

In particular, I noticed that when I choose `Run All` under `Cell` on the jupyter menu bar, playing with the sliders generated by calls to `@manipulate` reveals that many of these sliders don't work. Re-running a 'broken' cell's code fixes the issue, at least until subsequent cells are run.

The code below illustrates this issue. You should get errors if you try to use the sliders for cell 1 after running cell 1 and then cell 2.

Thank you for your help!

cell 1:
```
using Interact

function insert_block(A, i, j, what=7)
    B = copy(A)
    B[i:i+2, j:j+2] = fill(what, 3, 3)
    return B
end

A = fill(0, 10, 10)
n = size(A, 1)

@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i, j)
end
```

cell 2:
```
A = fill("Julia", 10, 10)
n = size(A, 1)

@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A, i,j, "####")
end
```

**Comment by JobJob** [comment]
Hi, the error that is occurring (`Cannot convert an object of type Int64 to an object of type String`) is happening because:
1) `A` is shared (all cells operate in the same workspace - i.e. you can refer to variables defined in previous cells) 
2) The type of `A` changes in the second cell to be an Array of Strings (it's type becomes `Array{String, 2}` to be precise) with the `A = fill("Julia", 10, 10)`

This means `insert_block(A, i, j)` call, with the default `what=7`, in cell 1, causes the `B[i:i+2, j:j+2] = fill(what, 3, 3)` to be an error, since `what` is an Int, so it's trying to set elements of a String Array to be Ints.

Changing cell 2 to this, for example, fixes it:
```
A2 = fill("Julia", 10, 10)
n = size(A2, 1)

@manipulate for i in 1:n-2, j in 1:n-2
    insert_block(A2, i,j, "####")
end
```

**Comment by xorJane** [comment]
That makes sense, thank you! I had incorrectly assumed `@manipulate` would capture the relevant state.

**Comment by JobJob** [comment]
Also, the `let` keyword creates a new scope. e.g. if you wrap both assignments to `A` in let blocks like so, then things work fine.
```
let 
    A = fill(0, 10, 10)
    n = size(A, 1)

    @manipulate for i in 1:n-2, j in 1:n-2
        insert_block(A, i, j)
    end
end
```
```
let 
    A = fill("Julia", 10, 10)
    n = size(A, 1)

    @manipulate for i in 1:n-2, j in 1:n-2
        insert_block(A, i,j, "####")
    end
end
```
