### ISSUE TITLE
Error with @manipulate

### ISSUE THREAD

**Issue by abhijithch** [JuliaGizmos/Interact.jl#223]
```
@manipulate for i=1:10
    i
end
```

gives the following error,
```
MethodError: convert(::Type{Array{Union{},1}}, ::Array{Union{},1}) is ambiguous. Candidates:
  convert(::Type{Array{Cdest,n}}, img::AbstractArray{T,n}) where {Cdest<:(ColorTypes.Colorant{T,1} where T), n, T<:Real} in ImageCore at /Users/abhijith/.julia/v0.6/ImageCore/src/convert_reinterpret.jl:105
  convert(::Type{Array{C,n}}, img::Array{C,n}) where {C<:ColorTypes.Colorant, n} in ImageCore at /Users/abhijith/.julia/v0.6/ImageCore/src/convert_reinterpret.jl:76
Possible fix, define
  convert(::Type{Array{Union{},n}}, ::Array{Union{},n})
```

**Comment by shashi** [comment]
It seems you have done `using Images`. This is an unfortunate ambiguity caused at https://github.com/JuliaGizmos/Interact.jl/blob/ce52c14a0772f46924cf16ef60b0a8ba08ebcfda/src/widgets.jl#L435 when converting an empty array of type `Array{Union{}}[]` (empty keyword args) to a Dict. The fix is to rewrite it a different way https://github.com/JuliaGizmos/Interact.jl/commit/4b24a0c521bd6276b4e95986f3be20c9d297ecc8

cc @timholy

**Comment by abhijithch** [comment]
Yes, I am doing `using Images`. Also thanks for the fix, it worked.
