### ISSUE TITLE
Allow sliders, etc. to be used directly as signals

### ISSUE THREAD

**Issue by ssfrr** [JuliaGizmos/Interact.jl#224]
If you have a slider created with `s = slider(...)`, you have to use `signal(s)` as an argument to `map`, `throttle`, etc. Would it make sense to have methods defined like `map(f::Function, s::Slider{T}) = map(f, signal(s))`? I'm not sure if there are cases where this usage would be ambiguous, but it seems like using a slider as a signal is a common thing you want to do.

**Comment by piever** [comment]
This is now allowed in Interact and InteractBase master (Julia 1.0 only, though part of the WebStack still needs to update to make this functional).

```julia
julia> using Interact

julia> s = slider(1:100);

julia> s[]
50

julia> map(t -> t/2, s)
Observable{Any}("ob_05", 25.0, Any[])

julia> isa(s, Observables.AbstractObservable)
true
```

I'm not closing this since Knockout, WebIO and InteractBase are not fully compatible with this yet, meaning, all functions from Observables just work on `Widget` but you can't pass a `Widget` to another widget yet, meaning `s = slider(1:100); w = slider(1:100, value = s)` still does not work.

**Comment by piever** [comment]
It should be possible to use widgets as `Observables` anywhere now, feel free to open issues specifically if you find cases where it fails.
