### ISSUE TITLE
"observe()" not defined?

### ISSUE THREAD

**Issue by dav2017** [JuliaGizmos/Interact.jl#230]
Hi,
I am trying to execute the code in notebook 01-Introduction.ipynb (via Jupyter)
The commands are:
    using Interact, CSSUtil, Observables, WebIO
then:
    s = slider(0:.1:1,label="Slider X:")
    display(s)
    display(observe(s));
but I get the following error:
UndefVarError: observe not defined

What's wrong?
Looking for functions in Interact, CSSUtil, Observables, WebIO ( e.g. name(Interact) ) I do not find the observe() function.

Julia version: 6.3

   Thanks for suggestions,

  Davide

**Comment by piever** [comment]
Interact is being refactored quite drastically: the currently available documentation reflects the latest unreleased version.

If you want to stick with the old version until the new one is released, you can use the notebooks you have locally in you `.julia/v0.6/Interact/doc/notebooks` folder.

If you feel adventurous and are happy to help catching new bugs/issues before the next release, you can try the latest unreleased Interact (which corresponds to the new docs) with `Pkg.checkout("Interact")` (if you don't have any prior Interact code, you may be better off learning the unreleased version so that you don't have to update your code in the future).

**Comment by dav2017** [comment]
Thanks for the suggestion; I will go with the unreleased version.

**Comment by piever** [comment]
Thanks a lot for helping troubleshoot the new Interact version, I'm closing this one: reopen / open other issues liberally if you find things in the docs that do not work after `Pkg.checkout("Interact")`
