### ISSUE TITLE
Widgets generated with map do not have same width as usual

### ISSUE THREAD

**Issue by ma-laforge** [JuliaGizmos/Interact.jl#273]
### Issue transfered over from https://github.com/JunoLab/Blink.jl/issues/171.

A `slider` that is generated with a `map` statement will not have the same size as standard `slider`s.

```
using Interact
using Blink

gmax = Observable(Float64(200)) #Maximum gain (user editable)

sld_G1 = slider(-10:1.0:100, label="Gain1 (dB)")
sld_G2 = map((_gmax)->slider(-10:1.0:_gmax, value=_gmax/2, label="Gain2 (dB)"), gmax)
sld_G3 = slider(collect(-10:1.0:100), label="Gain3 (dB)")

widgetlist = [sld_G1, sld_G2, sld_G3]
wnd = Window()
body!(wnd, vbox(widgetlist...))
```

![image](https://user-images.githubusercontent.com/11205411/47099763-fe6b9b80-d203-11e8-942f-d2a3072935d4.png)

@pfitzseb is suggesting that this might actually be an Interact issue.

**Comment by piever** [comment]
Yes, he is right, but actually I think the bug comes from WebIO. While I have no concrete idea what could be causing this, the recent WebIO cleanup fixes this. To try it out locally you should checkout both https://github.com/JuliaGizmos/WebIO.jl/pull/211 and https://github.com/JuliaGizmos/JSExpr.jl/pull/22

I'm not sure what the timeline is but that PR seems to be in a very usable state.

**Comment by piever** [comment]
Fixed by JuliaGizmos/WebIO.jl#211
