### ISSUE TITLE
Cannot throttle changes on mutable struct

### ISSUE THREAD

**Issue by ma-laforge** [JuliaGizmos/Interact.jl#274]
It seems that although I can create an `Observable()` that updates a global mutable structure, that observable cannot be throttled properly:

```
using Interact
using Blink

mutable struct MyType
	v::Float64
end

G1 = Observable(50.0)
sld_G1 = slider(-10:1.0:100, value=G1, label="Gain (dB)")
throttle1 = throttle(0.05, G1)

throttledobj = MyType(G1[])
mapG1 = map(G1) do _g1
	global throttledobj #Reference global object
	throttledobj.v = _g1 #Modify value to match value of G1
	return throttledobj #Always observe same object... but have maps signal changes
end
throttle2 = throttle(0.05, mapG1)

widgetlist = [sld_G1, "throttle1:", throttle1, "mapG1:", mapG1, "throttle2:", throttle2]
wnd = Window()
body!(wnd, sld_G1) #first call to body! does not always work.
body!(wnd, vbox(widgetlist...))
```

### Comments
 - If you pay close attention to the output, `mapG1` will update properly even though it is "pointing" to a `throttledobj`, but `throttle2` does ***not*** update, for some reason.
 - This does not appear to be a problem when `mapG1` returns a new object... only when you modify the contents of a mutable structure does the signalling seem to stop.

### Why do I even want this?
In my real-world case, `throttledobj` is basically a plot object that I modify with different sliders, etc.  I do not want to create a whole new plot object evey time a property changes.  I would rather keep referencing the same global object.

**Comment by piever** [comment]
It's due to [this line](https://github.com/JuliaGizmos/Observables.jl/blob/master/src/time.jl#L10). If after the "throttling time" has passed, the value of the `Observable` is the same as the one you'd want to update, it doesn't update. In this case `throttle2` is actually always having the correct value (meaning `throttle2[].v` will correctly return the value of the slider) because it always points to the same mutable struct. It simply does not send the signal to update the rendering on screen.

In terms of `Observables` semantics maybe you are right that it's a bit strange to impose that the value has changed in order to trigger a signal as we don't do that anywhere else. Maybe I should just remove the `(throttled[] != val)` condition.

**Comment by ma-laforge** [comment]
I personally find the side effect of that condition to be somewhat unpredictable.  It took me a while to figure out that it was happening on mutable structures only.

*So my vote is to remove this condition.*

If you really need this condition to further reduce "traffic", I would add an optional parameter when constructing the throttled `Observable`.

But as far as I can tell, we are already setting an upper bound for the update rate when we use the `throttled()` command, so I don't see this extra condition as a necessity.

**Comment by piever** [comment]
I agree that here it's mixing two concepts: "throttle" and "trigger only when different". There should be a special function only for "trigger when different" while `throttle` should respect what the input was doing. The `mutable struct` case (or any container that gets mutated) is very puzzling otherwise. I've opened a PR https://github.com/JuliaGizmos/Observables.jl/pull/28, let me know if it fixes your use case.
