### ISSUE TITLE
Widgets show but the plot isn't updated

### ISSUE THREAD

**Issue by juliohm** [JuliaGizmos/Interact.jl#282]
For a while now the `@manipulate` macro seems to not work on Jupyter. I get the widgets and can even slide them, but the plot is not updated.

Could you please help solve this issue?

**Comment by juliohm** [comment]
Is this package maintained or we should move to InteractNext.jl?

**Comment by piever** [comment]
I wouldn't recommend moving to InteractNext (I don't think it has been updated to Julia 1.0 and am not sure whether it will).

This package sees very little action because it basically just reexports InteractBase (that defines the widgets) and WebIO (that takes care of the Julia / JavaScript interaction in the various environments, say jupyter notebook, blink, mux).

If you have an issue with plots not updating, I would recommend specifying:

- InteractBase and WebIO versions
- what plotting package your using
- the exact commands

And to investigate a bit further whether the problem is specific to plotting, i.e. does:

```julia
@manipulate for i = 1:100
    i
end
```

update?

Also, is it specific to Jupyter Notebook? i.e. does

```julia
using Blink
ui = @manipulate for i = 1:100
    scatter(rand(i), rand(i))
end;
w = Window()
body!(w, ui)
```

update?

If the answer to any of the last two questions is yes, then I'd guess it's an issue with WebIO (as InteractBase is backend and plotting package agnostic) and should probably be reported there.

**Comment by juliohm** [comment]
Thank you @piever, I guess it is an issue with WebIO, the last snippet of code you shared using Blink works. I will see what I can do there. Thank you again for the clarification.
