### ISSUE TITLE
Slow performance when realoading large sections of an interface

### ISSUE THREAD

**Issue by rafaqz** [JuliaGizmos/Interact.jl#283]
I have an interface with over 100 checkboxes and 20-80 sliders. Most of these can be rebuilt to match the current model configuration selected in dropdowns.
It works amazingly well but the knockout.js reloads gets very slow at this scale. The delay can be 20 seconds! Strangely rebuilding a few hboxes of sliders and checks can take longer than the whole interface took to load in the first place.

Would this be a general Knockout.js issue or something to do with how Observables are interacting with Knockout? I'm wondering if there is a pattern of updating observables that would reduce this load time.

**Comment by piever** [comment]
I suspect with the two-side binding there may be some sort of "recurrent update" of some kind, but it's hard to tell without a MWE. Do you have a simple way of reproducing the issue?

Also, is this in Blink or in a notebook?

**Comment by piever** [comment]
If you observe a substantial difference between sliders and say textboxes, it may be because of the extra js setup to automatically convert slider widget from string (unfortunately in html input type number and range are actually strings...) to number.

I'm experimenting with the new Knockout version (4.0 alpha, see [repo](https://github.com/knockout/tko)) over at https://github.com/JuliaGizmos/Knockout.jl/pull/12 (you need to rebuild knockout after checking out the PR for it to download the correct library). Could you test that branch and see if it gets better for you?

**Comment by rafaqz** [comment]
I actually already noticed a massive speedup in performance in the last few months. I'm not sure which version caused this but reloading 50 sliders is basically instant now.
