### ISSUE TITLE
Button background still white using Bulma dark css

### ISSUE THREAD

**Issue by KestutisMa** [JuliaGizmos/Interact.jl#331]
I want to change Interact theme to dark.
```
using Blink, Interact
w = Window()
ui = button()
wait(w.content)
body!(w, ui);
```
I replaced ../assets/bulma.min.css" with this https://raw.githubusercontent.com/jenil/bulmaswatch/gh-pages/darkly/bulmaswatch.min.css
Button and background below color changed, but row which contains a button is still white:
![image](https://user-images.githubusercontent.com/29224758/62723095-88e1ed80-ba18-11e9-93f6-f062f65b4e0e.png)
Maybe somebody could advice a better way to change theme?

**Comment by KestutisMa** [comment]
Use case: Dark theme is useful when application is used on computer in lab performing fluorescence measurements when environment must be as dark as possible.

**Comment by piever** [comment]
Just replacing the css will not do it, since some parts of the css are not part of base Bulma, like the slider, so a proper dark theme would need to be implemented in [InteractBulma](https://github.com/piever/InteractBulma.jl) which is where theming support is being developed.

Are you on WebIO v0.8.9? I was hoping that something like https://github.com/JuliaGizmos/WebIO.jl/pull/329 would prevent this kind of bug.

**Comment by KestutisMa** [comment]
Yes, I am using WebIO v0.8.9.
I tried InteractBulma, copied https://github.com/jenil/bulmaswatch/blob/gh-pages/darkly/_variables.scss to 'darkly' directory in examples folder, got error:
```
julia> variables_file = joinpath(examplefolder, "darkly", "_variables.scss") # here you would use your own style
"/home/kest/.julia/packages/InteractBulma/0nxbg/src/../examples/darkly/_variables.scss"
julia> mytheme = compile_theme(variables = variables_file)
ERROR: Incompatible units: 'rem' and 'px'.
```

**Comment by KestutisMa** [comment]
Setting variable `$body-background-color: $black;` in file `_variables.scss` and compiling as described https://github.com/piever/InteractBulma.jl does same effect as in first post.

**Comment by KestutisMa** [comment]
Any updates on this issue?

**Comment by piever** [comment]
Sorry, I haven't had a lot of time to look into this, will try to have a go at it next week.

**Comment by piever** [comment]
It's actually a problem with Blink. Somehow Blink also sets their css in the Blink page. See https://github.com/JuliaGizmos/Blink.jl/pull/217 for a possible fix (you can apply the change locally after "devving" Blink to use it before that one gets merged).

I don't have a "dark theme" yet and adjusting BulmaSwatch themes takes a little bit because of that `rem` vs `px` nonsense with the extensions. You can probably take darkly/_variables.scss and only keep coloring things while throwing away anything concerning size (if you get it to work, I'd be happy to have a PR on InteractBulma :)). Or, as you already figured out, something as simple as:

```scss
$black: #000000;
$body-background-color: $black;
```

could make things much darker overall (even though it won't look great).

**Comment by piever** [comment]
Closing as things were fixed on Blink, see https://github.com/JuliaGizmos/Blink.jl/pull/217.

**Comment by KestutisMa** [comment]
Thanks, maybe it could be useful to add option set `:darkly` theme using command like `settheme!(:nativehtml)` https://juliagizmos.github.io/Interact.jl/latest/#CSS-framework-1 ?
