### ISSUE TITLE
Layout Options for Widgets

### ISSUE THREAD

**Issue by JobJob** [JuliaGizmos/Interact.jl#48]
Is there any way to control where widgets will appear when displaying more than one of them? E.g. say I wanted to have multiple checkboxes side by side. They seem to stack vertically by default. Something like hstack in Gadfly would be great. I guess this is somewhat related to https://github.com/JuliaLang/Interact.jl/issues/38 which I also would very much like to see. 

Would be happy to have a bash at it but not sure really where to start.

Ta!

**Comment by shashi** [comment]
Hey this is something I'm trying to address via [Canvas](/shashi/Canvas.jl). I'll update here when you can use it.

**Comment by JobJob** [comment]
Legend! Cheers.

**Comment by ma-laforge** [comment]
Just a general comment:

Interact almost needs to be able to provide a similar level of control over layout that toolkits like GTK+ provide if we (users) are to start building notebooks of moderate complexity.

I am starting to use ~half a dozen controls, and it is already quite difficult to keep everyting on one screen & easy for the user to understand.

...the problem is probably how one provides that level of control while maintaining the ease of use that Interact currently achieves.

**Comment by JobJob** [comment]
The PR linked above has hbox and vbox which I think should be a good start.

Also on master as of this week you have slider(...; orientation="vertical")

**Comment by JobJob** [comment]
@ma-laforge You can try it easily btw with 
```
Pkg.checkout("Interact", "jbj/hbox-vbox")
#then e.g.
hbox( slider(1:10), vbox(slider(11:20), checkbox()))
```

Would be good to get your feedback.

**Comment by ma-laforge** [comment]
Excellent.  I will probably want to use it in the near future.

**Comment by JobJob** [comment]
Ok good. This is now on master, would be great if you can try it out and let us know how it works for you.
